CREATE TABLE IF NOT EXISTS captials (
	id SERIAL PRIMARY KEY,
	country VARCHAR(45),
	captial VARCHAR(45)
);

CREATE TABLE IF NOT EXISTS flags (
	id SERIAL PRIMARY KEY,
	name VARCHAR(45),
	flag TEXT
);